"""Dashboard and platform state API routes."""

from __future__ import annotations

from datetime import datetime, timezone

from fastapi import APIRouter, Depends

from cybershield.api.auth import enforce_rate_limit, get_current_user
from cybershield.api.models import (
    DashboardMetricsResponse,
    DashboardSummaryResponse,
    FindingsListResponse,
    HealthResponse,
    ScanStatus,
    Severity,
)
from cybershield.api.routes.scan import scan_store


router = APIRouter(tags=["dashboard"])


@router.get("/api/v1/dashboard/summary", response_model=DashboardSummaryResponse)
async def get_dashboard_summary(
    _: str = Depends(get_current_user),
    __: None = Depends(enforce_rate_limit),
) -> DashboardSummaryResponse:
    """Return a high-level summary of security posture."""
    scans = await scan_store.all_scans()
    findings = [finding for scan in scans for finding in scan.findings]
    high_risk = [item for item in findings if item.severity in {Severity.CRITICAL, Severity.HIGH}]
    failed = [scan for scan in scans if scan.status == ScanStatus.FAILED]
    completed = [scan for scan in scans if scan.status == ScanStatus.COMPLETED]
    score = max(0, min(100, 100 - (len(high_risk) * 10) - (len(failed) * 5)))
    return DashboardSummaryResponse(
        generated_at=datetime.now(timezone.utc),
        total_scans=len(scans),
        completed_scans=len(completed),
        failed_scans=len(failed),
        open_findings=len(findings),
        high_risk_findings=len(high_risk),
        overall_risk_score=score,
    )


@router.get("/api/v1/dashboard/findings", response_model=FindingsListResponse)
async def list_findings(
    severity: Severity | None = None,
    _: str = Depends(get_current_user),
    __: None = Depends(enforce_rate_limit),
) -> FindingsListResponse:
    """List findings generated by scan jobs, optionally filtered by severity."""
    scans = await scan_store.all_scans()
    findings = [finding for scan in scans for finding in scan.findings]
    if severity is not None:
        findings = [finding for finding in findings if finding.severity == severity]
    return FindingsListResponse(findings=findings, total=len(findings))


@router.get("/api/v1/dashboard/metrics", response_model=DashboardMetricsResponse)
async def get_metrics(
    _: str = Depends(get_current_user),
    __: None = Depends(enforce_rate_limit),
) -> DashboardMetricsResponse:
    """Return aggregate operational security metrics."""
    scans = await scan_store.all_scans()
    findings = [finding for scan in scans for finding in scan.findings]
    findings_by_severity = {level.value: 0 for level in Severity}
    for finding in findings:
        findings_by_severity[finding.severity.value] += 1

    scans_by_type: dict[str, int] = {}
    for scan in scans:
        scans_by_type[scan.scan_type.value] = scans_by_type.get(scan.scan_type.value, 0) + 1

    completed = [scan for scan in scans if scan.status == ScanStatus.COMPLETED]
    success_rate = (len(completed) / len(scans) * 100.0) if scans else 100.0

    durations = [
        (scan.completed_at - scan.started_at).total_seconds()
        for scan in completed
        if scan.completed_at is not None
    ]
    mttr = (sum(durations) / len(durations)) if durations else 0.0

    return DashboardMetricsResponse(
        generated_at=datetime.now(timezone.utc),
        findings_by_severity=findings_by_severity,
        scans_by_type=scans_by_type,
        success_rate_percent=round(success_rate, 2),
        mean_time_to_complete_seconds=round(mttr, 2),
    )


@router.get("/api/v1/health", response_model=HealthResponse, tags=["health"])
async def health_check() -> HealthResponse:
    """Health endpoint for readiness and monitoring checks."""
    return HealthResponse(
        status="ok",
        version="0.1.0",
        timestamp=datetime.now(timezone.utc),
    )

