"""Pydantic models for network traffic and threat analysis."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Severity(str, Enum):
    """Severity levels for network findings."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class AlertCategory(str, Enum):
    """Alert categories produced by network scanners."""

    ANOMALY = "anomaly"
    CONFIGURATION = "configuration"
    THREAT = "threat"
    SIGNATURE = "signature"


class Protocol(str, Enum):
    """Common network protocols."""

    TCP = "tcp"
    UDP = "udp"
    ICMP = "icmp"
    DNS = "dns"
    HTTP = "http"
    HTTPS = "https"
    TLS = "tls"
    SSH = "ssh"
    FTP = "ftp"
    SMTP = "smtp"
    SMB = "smb"
    UNKNOWN = "unknown"


class NetworkAlert(BaseModel):
    """Normalized alert generated by network analysis."""

    alert_id: str
    category: AlertCategory
    severity: Severity
    title: str
    description: str
    src_ip: str | None = None
    dst_ip: str | None = None
    protocol: Protocol | None = None
    evidence: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class PacketSummary(BaseModel):
    """Parsed packet metadata used for flow reconstruction."""

    timestamp: float
    src_ip: str
    dst_ip: str
    src_port: int | None = None
    dst_port: int | None = None
    protocol: Protocol = Protocol.UNKNOWN
    size: int = 0
    payload_size: int = 0
    tcp_flags: str | None = None
    ja3: str | None = None


class NetworkFlow(BaseModel):
    """Bidirectional traffic flow reconstructed from packets."""

    flow_id: str
    src_ip: str
    dst_ip: str
    src_port: int | None = None
    dst_port: int | None = None
    protocol: Protocol = Protocol.UNKNOWN
    packet_count: int = 0
    total_bytes: int = 0
    payload_bytes: int = 0
    start_time: float = 0
    end_time: float = 0
    packet_timestamps: list[float] = Field(default_factory=list)
    ja3_fingerprints: list[str] = Field(default_factory=list)

    @property
    def duration_seconds(self) -> float:
        """Return flow duration in seconds."""
        return max(0.0, self.end_time - self.start_time)


class PortService(BaseModel):
    """Open/closed service details from nmap output."""

    host: str
    port: int
    transport: str
    state: str
    service: str | None = None
    product: str | None = None
    version: str | None = None
    extra_info: str | None = None


class SSLResult(BaseModel):
    """TLS configuration validation output."""

    host: str
    port: int
    valid: bool
    tls_version: str | None = None
    cipher: str | None = None
    certificate_subject: str | None = None
    certificate_issuer: str | None = None
    certificate_not_before: datetime | None = None
    certificate_not_after: datetime | None = None
    issues: list[str] = Field(default_factory=list)


class DNSSecurityResult(BaseModel):
    """DNS security checks for a domain."""

    domain: str
    dnssec_enabled: bool
    doh_supported: bool
    resolvers_tested: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class FirewallRuleFinding(BaseModel):
    """Issue discovered during firewall rule analysis."""

    rule_name: str
    severity: Severity
    issue: str
    recommendation: str


class TrafficReport(BaseModel):
    """Traffic analyzer output."""

    packets: list[PacketSummary] = Field(default_factory=list)
    flows: list[NetworkFlow] = Field(default_factory=list)
    alerts: list[NetworkAlert] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)


class ThreatReport(BaseModel):
    """Threat detector output."""

    alerts: list[NetworkAlert] = Field(default_factory=list)
    firewall_findings: list[FirewallRuleFinding] = Field(default_factory=list)
    dns_security: DNSSecurityResult | None = None
